apiVersion: v1
kind: ServiceAccount
metadata:
  name: global-service-account

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-cluster-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services", "namespaces" ,"deployments", "statefulsets","jobs","crontabs","nodes"]
  verbs: ["get", "watch", "list","update","post", "batch"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: global-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: global-service-account # Name is case sensitive
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: global-cluster-role
  apiGroup: rbac.authorization.k8s.io

  